//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dbKP_football
{
    using System;
    using System.Collections.Generic;
    
    public partial class coaches
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public coaches()
        {
            this.teams = new HashSet<teams>();
        }
    
        public int C_ID { get; set; }
        public string C_SURNAME { get; set; }
        public string C_NAME { get; set; }
        public string C_NATIONALITY { get; set; }
        public System.DateTime C_DATEOFBIRTH { get; set; }
        public int L_ID { get; set; }
    
        public virtual leagues leagues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<teams> teams { get; set; }
    }
}
