//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dbKP_football
{
    using System;
    using System.Collections.Generic;
    
    public partial class footplayers
    {
        public int FP_ID { get; set; }
        public int T_ID { get; set; }
        public string FP_SURNAME { get; set; }
        public string FP_NAME { get; set; }
        public System.DateTime FP_DATEOFBIRTH { get; set; }
        public string FP_NATIONALITY { get; set; }
        public string FP_POSITION { get; set; }
        public int FP_TEAMNUMBER { get; set; }
        public double FP_GROWTH { get; set; }
        public double FP_WEIGHT { get; set; }
        public string FP_WORKINGLEG { get; set; }
    
        public virtual teams teams { get; set; }
    }
}
