//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dbKP_football
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_KP_FootballEntities : DbContext
    {
        public db_KP_FootballEntities()
            : base("name=db_KP_FootballEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<coaches> coaches { get; set; }
        public virtual DbSet<footplayers> footplayers { get; set; }
        public virtual DbSet<leagues> leagues { get; set; }
        public virtual DbSet<stadiums> stadiums { get; set; }
        public virtual DbSet<teams> teams { get; set; }
    }
}
