//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dbKP_football
{
    using System;
    using System.Collections.Generic;
    
    public partial class teams
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public teams()
        {
            this.footplayers = new HashSet<footplayers>();
        }
    
        public int T_ID { get; set; }
        public int L_ID { get; set; }
        public string T_NAME { get; set; }
        public string T_TOURNIER { get; set; }
        public int T_QUAFOOTPLAYERS { get; set; }
        public int T_YEAROFFOUND { get; set; }
        public int S_ID { get; set; }
        public int C_ID { get; set; }
    
        public virtual coaches coaches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<footplayers> footplayers { get; set; }
        public virtual leagues leagues { get; set; }
        public virtual stadiums stadiums { get; set; }
    }
}
